---
title: "Solutions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Solutions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains solutions to exercises.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
s_sol_url <- "https://charlotte-ngs.github.io/pigsciencess2022/sol/"
tbl_sol <- tibble::tibble(Nr = c(1, 2, 3),
                          Date = c("2022-04-27",
                                  "2022-05-04",
                                  "2022-05-11"),
                          Topic = c(
                           paste0("[Introduction to Breeding Programs](", s_sol_url, "psb_ex01_sol.pdf)", collapse = ""),
                           paste0("[Model Selection](", s_sol_url, "psb_ex02_sol.pdf)", collapse = ""),
                           paste0("[Variance Components](", s_sol_url, "psb_ex03_sol.pdf)", collapse = "")
                          ))
knitr::kable(tbl_sol)
```



```{r latest-change, echo=FALSE, results='asis'}
cat(rmdhelp::get_latest_change())
```
