---
title: "Additional Material"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Additional Material}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This page contains additional material like links to slides, video recordings, and more ...


## Slides

```{r, echo=FALSE}
s_sl_url <- "https://charlotte-ngs.github.io/pigsciencess2022/sl/"
tbl_sl <- tibble::tibble(Nr = c(1, 2),
                         Date = c("2022-04-27",
                                  "2022-05-04"),
                         Topic = c(
                           paste0("[Introduction to Breeding Programs](", s_sl_url, "l01_psb_intro.pdf)", collapse = ""),
                           paste0("[Model Selection and Variance Components](", s_sl_url, "l02_psb_modsel_varcomp.pdf)", collapse = "")
                         ))
knitr::kable(tbl_sl)
```



## Videos

```{r, echo=FALSE}
tbl_video <- tibble::tibble(Nr = c(1),
                            Date = c("2022-04-27"),
                            Topic = c(
                              "[Introduction to Breeding Programs](https://youtu.be/cF75-GB6Mz8)"
                            ))
knitr::kable(tbl_video)
```


## Misc

```{r, echo=FALSE}
s_misc_url <- "https://charlotte-ngs.github.io/pigsciencess2022/misc/"
tbl_misc <- tibble::tibble(Nr = c(1),
                           Date = c("2022-04-27"),
                           Topic = c(
                             "[SRF 10vor10 Report on breeding](https://www.srf.ch/play/tv/redirect/detail/51803eb1-9313-45f1-bee3-833fc3f79d97)"
                           ))
knitr::kable(tbl_misc)
```


```{r latest-change, echo=FALSE, results='asis'}
cat(rmdhelp::get_latest_change())
```
